### PR TITLE
Validate required arguments

### LINKED ISSUE #14: Required arguments not working
Required arguments don't raise an error when no argument is passed.

Add the following line at the bottom of `examples/complex.cr` to reproduce this bug.

```crystal
Complex.run ""
```

There is no error even though the argument `required`, which is `required`, is not passed. The argument is defined below.

```crystal
  define_argument required : Int32, required: true
```

This is my `shards.yaml`.

```yaml
name: kato
version: 0.1.0

authors:
  - Ravern Koh <ravernkoh@gmail.com>

description: |
  Toy virtual machine written in Crystal

targets:
  kato:
    main: src/kato/cli.cr

dependencies:
  admiral:
    github: jwaldrip/admiral.cr

development_dependencies:
  cake:
    git: https://github.com/ravernkoh/cake.git
    branch: master

license: GPL-3.0
```

Edit: Made a mistake in the example to reproduce, was originally `Complex.run —required woah”`.

### PR DESCRIPTION
**Pull request by djmaze**
fixes #14, #15

### CODE REVIEW

**Comment by djmaze** [comment]
Just recognized this is not yet fully working. Let me have a look at it.

**Comment by djmaze** [comment]
Okay, looks better now.

**Comment by ceritium** [comment]
I would love see this PR merged soon.

**Comment by ravern** [comment]
Merging soon?

**Comment by absolutejam** [comment]
Any update on this?

**Comment by jwaldrip** [comment]
Sorry about the delay here. Merging now. LGTM

**Pull request merged**
